# Where should we write the GIF?
Output "tng --text-color light_blue.gif"
Set PlaybackSpeed 1.0
Set Framerate 25

# Set up a 1200x600 terminal with 46px font.
Set FontSize 16
Set Width 854
Set Height 480

# Type a command in the terminal.
Type "tng --text-color light_blue"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 60s
